### ISSUE TITLE
Investigate: Missing referendum committee expenditure data

### ISSUE THREAD

**Issue by anlawyer** [caciviclab/disclosure-backend-static#245]
Oakland Neighbors United: No on Measure Q - this committee has expenditure data reported, but the site shows $0. Suzanne's data says their 460 form reported $95,298.

![Screen Shot 2020-05-05 at 8 31 01 PM](https://user-images.githubusercontent.com/28023047/81136925-c5903600-8f11-11ea-9451-e5e6b11dd85c.png)

**Comment by mikeubell** [comment]
They are missing Accrued Expenses (Schedule-F) and non-monetary contributions (Shedule-C)
The quick way out of this would be to just use the summary number (line 11) for referendum as we don't categorize expenses.  @tdooner

**Comment by mikeubell** [comment]
Aha! We actually do look at accrued expenses and nonmonetary adjustments BUT we iterate through the list of committees with regular expenses and add these values to that.  This committee does not have any regular expenses.

**Comment by mikeubell** [comment]
The problem here is that the Summary table does not include the information that is in the other schedules from 460.  e.g. Ballot Number, Support/Oppose, etc.  A committee must have at least one item in the Schedules in order to get that information.  If it did not have anything in the schedules then its income and expenses would be 0, so we probably don't care.
Still it would be nice if netfile included more info in the Summary table.

**Comment by tdooner** [comment]
Thanks for taking care of this!
