### ISSUE TITLE
Include candidate's committee Id in the candidate endpoint

### ISSUE THREAD

**Issue by adborden** [caciviclab/disclosure-backend-static#37]
#20 is building an endpoint to get the contributors to a committee. In order to build the candidate contributors page https://github.com/caciviclab/disclosure-frontend/issues/162, we need to know the candidate's committee Id. We currently include the `committee_name` and that is a reasonable way to match the candidate to a committee.

**Comment by adborden** [comment]
@sfdoran I've seen some cases in federal elections where a candidate has multiple committees, is that possible for oakland/california?

**Comment by sfdoran** [comment]
For campaigning purposes under the CA Political Reform Act, a candidate or officeholder must establish one controlled committee with one bank account for each election. All campaign contributions must be deposited in and all expenditures must be made from that campaign bank account. 

Local candidates and/or officeholders may also control a legal defense fund, or officeholder expense committee (if provided by local ordinance). The Oakland Campaign Reform Act does allow officeholder accounts but and you'll see those accounts in the data as well because they also have to file 460s, but that money cannot be used for campaigning purposes. I
