### ISSUE TITLE
Define an API for Search

### ISSUE THREAD

**Issue by tdooner** [caciviclab/disclosure-backend-static#77]
Hey @adborden, we probably need to figure out an API for the search feature specified here:

https://docs.google.com/document/d/1fu0GMbicaERV_7R0aoLBw1ST-yFM1P3K_8mqhDTOcGs/edit#heading=h.chyrjd53oksh

It's possible that we can just query the cloud search provider directly... and thus not need to do an API on the backend. I've never designed a search API including dropdown results and other stuff, so I'd prefer to avoid that if we can just query the cloud search engine directly.

**Comment by adborden** [comment]
If you want those special search features like quoted phrases, booleans, and proximity search, I suggest building an API on the back end rather than call directly to the search provider. Start simple, with an API that just passes the query through to the [query_string](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html) filter, which supports some [fancy syntax](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#query-string-syntax) out of the box, which you can then iteratively improve.

**Comment by tdooner** [comment]
Agreed - let's make a proxy API for whatever backend provider is doing the search. That'll keep the client simpler and allow us to iterate on the search index structure a lot easier.

It looks like we can accomplish most of all we want with just a simple `GET /search?q=[query]` with an optional `&limit=[limit]` for purposes of an autocomplete dropdown.

It could return something like this:

```json
{
  "results": 10,
  "hits": [
    ...
  ]
}
```

and each hit looks like:

```json
{
  "id": 123,
  "type": "contributor",
  "name": "Foo Bar",
  "_": "whatever other fields for each type of data"
}
```

I think this would be easy to instantiate into an API response object with Angular/Swagger, right?

A couple questions I still have are 1) what fields are required for each type of result, and 2) result highlighting. Do we want to bold the part of the result that matches the search query? Maybe a nice-to-have for later.

**Comment by TyGuy** [comment]
Hey @tdooner I don't know about the specifics of the fields for each type of result, but I have one thought on high-level structure:

I think `"results"` and `"hits"` sound like the same thing. I would suggest `"count"` for count, and if you are worried about limiting/pagination, then have a `"count"` which denotes the number of items returned, and a `"total_count"` for the total number of results that matched (with some other metadata on pagination, etc. as well). I think `"hits"` is fine as a key, and makes sense since it's also what elasticsearch itself seems to return.

Regaring result highlighting, not sure if your question is about the api returning a "highlighted" match or if the JS/front-end should do that. I think if it was to be a feature, it's probably the responsibility of the front-end, and since it has access to the query, things can easily be bolded via substring/regex matching.
